### ISSUE TITLE
Feature Request, auto format/unformat when loading and saving a file

### ISSUE THREAD

**Issue by Skrell** [BdR76/CSVLint#11]
First off, I LOVE this plugin!   I have to edit csv files regularly and this is hugely helpful!  The 1 feature I'd LOVE to see is an auto-format/auto-unformat option whereby when you open a csv file it automatically applies the format options and upon saving it undoes the formatting options.  That way the user couldn't mess up the file by formatting it a specific way but still have the advantages of formatting while working with it!

**Comment by BdR76** [comment]
Thanks, nice to hear you found the plug-in useful.

But I don't quite understand the features you're describing though. With "auto-format/auto-unformat" do you mean convert the file when opening to a different format, and then convert back to the old format when saving?

Like, change the datetime values to something plus make it vertically align when opening, and then when saving convert the file back to whatever the formats were when opening?

**Comment by Skrell** [comment]
That is correct.  I think that would make working with csv files seamless
and far more user friendly.  Thoughts?

**Comment by BdR76** [comment]
I've thought about it some more, what you're asking is storing the file transformations processes and this would require adding a complete ETL workflow. This goes beyond the scope of this plug-in I'm afraid. The CSV Lint plug-in is intended to quickly inspect and find errors in CSV files, with some limited features to handle the most common formatting issues.

To do what you're suggesting, I think you should look into ETL tools like OpenRefine or SSIS or maybe just Power Query in Excel or else TalenD (not familiar with that last one), which are probably better suited for what you're describing.

So I'll close this issue for now.

**Comment by Skrell** [comment]
I've never heard of "ETL tools" so I'll look them up!  Thanks for the tip!
