### ISSUE TITLE
First row color formatting when entries have newlines

### ISSUE THREAD

**Issue by dpwilt** [BdR76/CSVLint#13]
Hi BdR76!  Thanks for a great plugin for npp.  I have an issue when I open a .csv file that has newlines embedded in some column entries.  It seems that the color formatter is confused about the first row.  Minimal working example below.  Thanks again!! dpwilt
![test2](https://user-images.githubusercontent.com/8657501/152001055-b51f9ca1-7814-48a9-a10b-530e09a38ccb.png)

**Comment by juergen-tschandl** [comment]
What you see there is just the line with the cursor in it. The background color for the cursor line currently does not use alpha. You could switch to foreground color mode in the CSVLint settings.

**Comment by BdR76** [comment]
This issue was fixed by @juergen-tschandl who graciously added a transparent cursor line. It is available in the 0.4.5 update which will be available in the Plugins admin in Notepad++ soon (or manually download it [here](https://github.com/BdR76/CSVLint/releases)).

**Comment by dpwilt** [comment]
Thanks!
