### ISSUE TITLE
Convert to SQL option  column name is enclosed with ` instead of []

### ISSUE THREAD

**Issue by spk33** [BdR76/CSVLint#15]
thanks for the CSVLint plugin
i would like to report and issue in Convert to SQL option 
the  column name is enclosed with ` instead of [] under create table and insert into script part section

![image](https://user-images.githubusercontent.com/7496315/156275783-07463a49-b6f4-458f-a232-2d8ba71f20c3.png)

**Comment by spk33** [comment]
![image](https://user-images.githubusercontent.com/7496315/156277122-af2d35bb-48c3-4edd-abbd-e9f78c0e7446.png)
Found SQLansi option which helped in generating script for SQL format

**Comment by BdR76** [comment]
Thanks for mentioning this, the next update will have a dialog where you always have to choose the database type. Then it's more clear what the plugin is doing and what options it's using.
