### ISSUE TITLE
Downloading 0.4.5 release. Fail to unpack

### ISSUE THREAD

**Issue by JockeJarre** [BdR76/CSVLint#18]
I tried to download the 0.4.5 (x64) release from Github a couple of times. Version 0.4.4 (x64) works well.
When I try to unpack either 7zip or Windows explorer shows an error:

![image](https://user-images.githubusercontent.com/12571104/159729972-5edf50b4-7fcb-4b73-b7ef-c60bfaf2d555.png)
![image](https://user-images.githubusercontent.com/12571104/159730660-47192b5d-eb2f-43ed-b49c-50f325798199.png)

**Comment by BdR76** [comment]
Thanks for the e-mail. This seems like an issue that is not related to the
plug-in itself, but rather some access or admin / userrights issue.
This can have a couple of causes
* Did you close Notepad++ while doing this? When Notepad++ is opened the OS
won't let you overwrite any DLL files that are in use (i.e. the old version
of CSVLint.dll)
* Do you have admin access to the program files folder? (note; I assume
you're trying to copy the file to the \Program
Files\Notepad++\plugins\CSVLint\ folder)
* You could try to open 7zip as admin, so right click and select "run as
admin".

Let me know if that helps

cheers,
Bas
