### ISSUE TITLE
Notepad++ > 8.3.3 Scintilla 5 updates remove external lexer support

### ISSUE THREAD

**Issue by vinsworldcom** [BdR76/CSVLint#19]
Running latest Notepad++ development build:

![image](https://user-images.githubusercontent.com/9657169/160893767-3e2fc54c-a7b4-4501-a831-882ea9ed0021.png)

See [here](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/41a5bf0245b53e74186e49a21adec2c518587b5c).

**Comment by BdR76** [comment]
Oh man.. ☹ That is a real shame, the syntax highlighing is one of the best features of this plug-in. Thanks for letting me know, I've posted a questoin about it [on the forum](https://community.notepad-plus-plus.org/topic/22787/remove-the-external-lexer-support-due-to-scintilla-5).

**Comment by BdR76** [comment]
I didn't have the time to work on an update for this issue until now but it's fixed. See the releases for [the latest version](https://github.com/BdR76/CSVLint/releases). You can download the [new CSVLint version 0.4.5.1 here](https://github.com/BdR76/CSVLint/releases/tag/0.4.5.1)

The plugin list was [also updated](https://github.com/notepad-plus-plus/nppPluginList/pull/443) so it will be available in the next Notepad++ update. Btw I've also updated this [lexer example project](https://github.com/BdR76/NppPluginLexerExample)
