### ISSUE TITLE
Number of columns with quotes not valid

### ISSUE THREAD

**Issue by becabbage** [BdR76/CSVLint#2]
First of all, thanks and congratulations for the helpful and great plugin. 

I found an issue when validating columns that contain quoted delimiter-characters,

**Quote character is:** " (double-quotes)
**Delimiter character is:** , (comma)

This is my **validation config**:
```
Format=CSVDelimited
ColNameHeader=True
Col1=a Text Width 10
Col2=b Text Width 10
Col3=c Text Width 10
```

This is my **test data**:
```
a,b,c
a1,a2,a3
"a1","a,2","a3"
"a1","a2","a3"
```

The 3rd line throws an validation error, although the 2nd field **"a,2"** is quoted validly.

This is the **error-message**:
```
** error line 3: Too many columns
Inspected 4 lines, 1 data errors found, time elapsed 00:00:00.000
```

Would be great if you could look into this.

Thanks & best regards, 
Bernhard

**Comment by BdR76** [comment]
Thanks for your feedback, the support for quoted strings is on the list of missing features. I will continue working on this plugin again soon, and this feature will be at the top of the priority list.

**Comment by BdR76** [comment]
FYI quoted strings are now supported, plus it's now easier to spot any missing quotes in combination with the new syntax highlighting feature

**Comment by becabbage** [comment]
Yeah, that's amazing. Thanks!
