### ISSUE TITLE
Does not work with Notepad++ 8.4

### ISSUE THREAD

**Issue by tahendry** [BdR76/CSVLint#22]
Hi there

Unfortunately, the plugin does not work with the newest version anymore.
8.3.3 was working, 8.4 not anymore. 

cheers
Reto

**Comment by BdR76** [comment]
Thanks for letting me know, I was [aware of the issue](https://community.notepad-plus-plus.org/topic/22787/remove-the-external-lexer-support-due-to-scintilla-5) but didn't have the time to work on an update until now. It's fixed and the plugin list [was updated](https://github.com/notepad-plus-plus/nppPluginList/pull/443) so it will be available in the next Notepad++ update. Notepad++ is updated irregularly, could be a couple of days, could be in a week or more depending on bugfixes etc.

But you can also download the [new CSVLint version 0.4.5.1 here](https://github.com/BdR76/CSVLint/releases/tag/0.4.5.1.) and install it manually. Unzip and replace the CSVLint.dll in your `.\Program Files\Notepad++\plugins\CSVLint\` folder.

**Comment by flotux2** [comment]
@BdR76: Thanks for fixing the problem. I appreciate it because it is a development in your spare time.
