### ISSUE TITLE
Feature Request: Manually specify Header Row/Separator character when detecting metadata

### ISSUE THREAD

**Issue by tgardner42** [BdR76/CSVLint#28]
Currently when there is no difference in data types between header and data in any column, CSVLint assumes there is no header row. While this is completely understandable, it would be beneficial to be able to specify that a header row exists, assuming that this behavior is intended. A checkbox in the CSVLint window would be most preferable in my mind but even a toggle in the plugin menu would be very helpful.

ColNameHeader=False
```CSV
Job Name, GUID, Error Message, Run in Audit Mode
"CONTACT_UPDATE","1234567890abcdef","Failed to process; reasons","No"
```
ColNameHeader=True
```CSV
Job Name, GUID, Error Message, Run in Audit Mode,Thing
"CONTACT_UPDATE","1234567890abcdef","Failed to process; reasons","No","1"
```

Windows 10 21H2 x64, NPP 8.4.1 32-bit, CSVLint 0.4.5.1 in case it matters. Thanks for making such a handy plugin!

**Comment by tgardner42** [comment]
I have installed v0.4.5.2 and have confirmed that it properly detects the header row on a couple of the files I noticed this behavior with. Thank you for the quick resolution!

**Comment by BdR76** [comment]
I've updated the CSV Lint plug-in to version 0.4.5.3 and it contains a new feature where you can manually override the automatic column detection

It will be available in Plugin Admin in the next Notepad++ update eventually, or you can also install it now by going to the [releases page](https://github.com/BdR76/CSVLint/releases), download the most recent zip and follow the [steps described here](https://github.com/BdR76/CSVLint#how-to-install).
