### ISSUE TITLE
Minimal quotes, not escaping quotes itself

### ISSUE THREAD

**Issue by oliver-pola** [BdR76/CSVLint#29]
I got a CSV, Format=Delimited(;), from PowerShell Export-CSV with UseQuotes=AsNeeded (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-csv?view=powershell-7.2) and want to apply the same rule with your reformat feature. So I suppose UseQuotes=AsNeeded translates to Minimal quotes, but it does not escape the quotes itself by double-double-quotes.

I have content to start some executables with arguments in a different column (one arguments column). And it looks like this:
_arguments: arg1, arg2 with spaces_
will result in CSV to:
`...;"arg1 ""arg2 with spaces""";...`

If I apply reformat with minimal quotes I get:
`...;arg1 "arg2 with spaces";...`

**Comment by BdR76** [comment]
Thanks for posting this issue. You're right this was a bug, it only checked for the separator character, not the quote character. It's [fixed now](https://github.com/BdR76/CSVLint/blob/master/CSVLintNppPlugin/CsvLint/CsvEdit.cs#L36) and will be available next update

**Comment by BdR76** [comment]
fyi the CSV Lint plug-in was updated to version 0.4.5.3 which is available in the [releases page](https://github.com/BdR76/CSVLint/releases), which also contains the bugfix for this issue.

Eventually in the next Notepad++ update it will be available in Plugin Admin, but you can also install the latest plugin version manually by going to the [releases page](https://github.com/BdR76/CSVLint/releases), download the most recent zip and follow the [steps described here](https://github.com/BdR76/CSVLint#how-to-install).
