### ISSUE TITLE
column split doesn't quote strings containing separator char in new columns

### ISSUE THREAD

**Issue by molsonkiko** [BdR76/CSVLint#35]
I was playing around with the column split feature, and I noticed that while it works as advertised in general, there's a minor bug where strings containing the separator char are not enquoted in the new CSV produced by the column split feature.
This seems pretty nitpicky, so probably a low priority to address. Thanks for making an awesome plugin!

For example, I have a CSV file:
![silly_example before dummy split by cities](https://user-images.githubusercontent.com/46202915/182873666-89ecf417-266c-4734-85b3-a7d3ba943291.PNG)
If I split the "cities" column using the "decode multiple value" option with the values "FUDG;BUS;GOLAR;YUNOB;MOKJI" I get
![silly_example after dummy split by cities](https://user-images.githubusercontent.com/46202915/182874029-aa386c40-c999-488a-ab37-59e3bcedf4d9.PNG)
Since the separator char is present in one of the new columns, we get some weirdness.

A similar bug occurs whenever I use any of the other column split options (e.g., split on position 3, split on character "t"); values containing the separator char are not wrapped in quotes.
If I choose not to discard the original column, the quotes stay in place in the original column but not the generated columns:
![silly_example after dummy split by cities keep og column](https://user-images.githubusercontent.com/46202915/182876552-316e16e6-1bda-478a-ba4a-110612666535.PNG)

**Comment by BdR76** [comment]
Thanks for submitting the issue with the detailed description. 👍 You are correct, the split column function didn't check for separator or quote characters. I've looked into it and fixed the `SplitColumn` function. The bugfix will be available in the next update

**Comment by BdR76** [comment]
The bugfix is available in the new release v0.4.5.4 [see releases](https://github.com/BdR76/CSVLint/releases)
