### ISSUE TITLE
No "Detect Columns" option available

### ISSUE THREAD

**Issue by SpiderManAPV** [BdR76/CSVLint#37]
I don't have a "detect columns" option in CSV Lint.  I was trying to get CSV Lint to recognize a CSV file and was unable to get it to detect the columns in said file. I eventually figured out that specific issue was caused by the bug mentioned in #36, but during the process of trying to get it to detect my file I realized I don't have any option to detect columns. Images attached.

![image](https://user-images.githubusercontent.com/18339186/189666484-b6ad1a95-4f0f-448f-8ed5-ec0d49b7c200.png)
![image](https://user-images.githubusercontent.com/18339186/189667044-4b16a436-8930-413e-b104-f6d11d1d9bc1.png)

**Comment by BdR76** [comment]
Which version of the plugin do you have installed? You can check under menu `Plugins -> CSV Lint -> About` and also under `? -> Debug info`.

I suspect it is v0.4.5.2 or earlier, that version didn't have the "auto-matic" checkbox yet. In the older versions you can only press the "Refresh from data" button to automatically detect columns (or painstakingly type in the schema.ini metadata for all columns by hand..)

In the newer version you can disable the checkbox to override the automatic column detection and specify the column separator character. You can go to the `Plugins -> Plugins Admin` dialog and "Updates" tab to update the CSV Lint plug-in. If there isn't an update, then you probably need to update Notepad++ to the most recent version.

**Comment by BdR76** [comment]
Btw the buton "Refresh from data" was relabeled "Detect columns", but it is the same button

**Comment by SpiderManAPV** [comment]
The plugin is 0.4.5.2 as you guessed. Does it need to be manually updated? There aren't any updates available for the plugin when I check in the NP++ plugin admin menu.

**Comment by BdR76** [comment]
With every Notepad++ version update, the [list of available plugins in the Plugin Admin](https://github.com/notepad-plus-plus/nppPluginList) is also updated. It keeps an internal list of plugins + versions + checksums, this is for security reasons to prevent hackers from distributing malware plugins.

If you only see CSV Lint plugin v0.4.5.2 (older version) in Plugin Admin then you probably also have an older version of Notepad++ installed. So yes, then you can only manually update the plugin, either that or update Notepad++ to the most recent version.

**Comment by SpiderManAPV** [comment]
That makes sense. I've updated and the detect columns button is now available. Thanks

**Comment by Redpossum** [comment]
I know this is closed, but just wanted to say thank you. I was having the same problem and this solved it. Yay GitHub!
