### ISSUE TITLE
Reformatting changes text encoding 

### ISSUE THREAD

**Issue by grenelt** [BdR76/CSVLint#52]
![grafik](https://user-images.githubusercontent.com/474834/223742554-54060327-1bf9-4d2e-9b0a-1807cb93cf3c.png)

File is ANSI before and after, but it looks like it's going through a double conversion to UTF and back...

**Comment by Friedi** [comment]
Notepad++: **8.5 (x64)**
CSV Lint plugin version: **0.4.6.3ß**

I can confirm this behavior. I used the following reformatting setting

![image](https://user-images.githubusercontent.com/3397608/224662281-10d44381-de84-4dac-867d-d596c82425b5.png)

> File is ANSI before and after, but it looks like it's going through a double conversion to UTF and back...
