### ISSUE TITLE
Lock first row when scrolling

### ISSUE THREAD

**Issue by B5A7** [BdR76/CSVLint#74]
Hi

Would this be a possibility, like the feature in Excel?

Thanks
Brad

**Comment by BdR76** [comment]
I don't think something like the Freeze Panes of Excel is technically possible in Notepad++. The only thing I can think of is using folding/collapsable groups.

Currently, the plugin doesn't use the folding feature at all, so I mean like the [+] signs on the left next to the row number, for example when you open an XML file. Theoretically the CSV plug-in could mark each 10 or 50 rows (or something like that) as folding groups so are foldable/collapsable. And then the top row header names would also be one folding group so you can leave that one open/visible.

Still though, this wouldn't come close to the "Freeze Panes" functionality of Excel.

**Comment by B5A7** [comment]
No worries.  I am dealing with files where you have several Y/N flags in a row and always struggle to remember which column is which.  Thanks anyway for your consideration.  Still a great product.

**Comment by BdR76** [comment]
I was thinking about some sort of "Columns Highlight" function. So you could set the syntax highlighting to only certain column(s).

So for example, if you select column 5, 7, 12 then everything would be white and only the values of columns 5, 7 and 12 would have a color. That would be useful in your case as well right?

Not sure if I can add this feature though, just speculating.

**Comment by B5A7** [comment]
Found a workaround - https://stackoverflow.com/questions/38348383/how-can-i-fixate-a-number-of-rows-as-a-sort-of-header-in-notepad.
Cheers
