### ISSUE TITLE
Doesn't work in notepad++ v8.1.9 CSVLint.xml is missing

### ISSUE THREAD

**Issue by jorgemvg** [BdR76/CSVLint#9]
Hello,
It doesn't work in notepad++ v8.1.9

I tried with 32 and 64 bit version
![CSVlintError](https://user-images.githubusercontent.com/5809257/139736966-f77d9473-a99d-4570-ac24-a636dff1ef32.png)

**Comment by BdR76** [comment]
Same issue as https://github.com/BdR76/CSVLint/issues/6 which was fixed, but the Plugin Admin list still points to the old 0.4.1 version. The plugin list [was updated](https://github.com/notepad-plus-plus/nppPluginList/pull/378) but this won't be available until the next Notepad++ update. The official updates are irregular afaik, depending on bugfixes, backlog etc.

In the mean time you can manually download the [new version 0.4.2 here](https://github.com/BdR76/CSVLint/releases/tag/0.4.2) unzip and replace the CSVLint.dll in your `.\Program Files\Notepad++\plugins\CSVLint\` folder. Also, if you're using dark mode you can [manually adjust the color scheme](https://github.com/BdR76/CSVLint/tree/master/docs#syntax-highlighting-colors).

Btw to avoid people posting this same issue, I'll leave this one open for now until the new update is available.

**Comment by BdR76** [comment]
The plugin was updated [CSV Lint v0.4.3](https://github.com/BdR76/CSVLint/releases) which fixes this issue.

Notepad++ was also updated yesterday; `Notepad++ v8.1.9.1` has the latest `Plugins Admin` which includes [CSV Lint v0.4.3](https://github.com/BdR76/CSVLint/releases). If you have Notepad++ v8.1.9 or older you can update the plugin by [copying the .DLL file manually](https://github.com/BdR76/CSVLint#how-to-install).
