### ISSUE TITLE
Reformat, Sort and Add Column changes CRLF to LF

### ISSUE THREAD

**Issue by rdebath** [BdR76/CSVLint#91]
Even if you untick all the options in "Reformat Data" the process removes all CR characters from the file.

This upsets several Windows importers including (sometimes) Excel. If Excel has a multiline value in a column it'll use "LF" for the lines in a column and "CRLF" at the end of a line.

**Comment by BdR76** [comment]
Thank you for posting this issue. You are right, the same thing happens for `Sort` and `Add column`. I can't believe I never noticed this.

I've fixed it and it will be available in the next release. In the meantime you can download the [beta (β3) version of the DLL here](https://github.com/BdR76/CSVLint/tree/master/CSVLintNppPlugin/bin)

**Comment by BdR76** [comment]
I felt like this issue was important enough for anothjer update, so I've released a [new version v0.4.6.7](https://github.com/BdR76/CSVLint/releases) that includes this fix
