### ISSUE TITLE
Not getting highlighting

### ISSUE THREAD

**Issue by MnHebi** [BdR76/CSVLint#92]
The .csv files I wish to edit(specific to a game called Starsector) never get highlighted. Uploaded an example csv to showcase the problem.
[ship_data.csv](https://github.com/user-attachments/files/16057640/ship_data.csv)

**Comment by BdR76** [comment]
Sorry I overlooked this issue over the summer. Haven't heard of the game [Starsector](https://www.reddit.com/r/starsector/), but anyway I can not reproduce your issue. When I open the file the columns are detected correctly and the syntax highlighting works. Does the syntax highlighting work when you manually select menu item `Language > C > CSV Lint` ?

If you still encounter the issue then I need a bit more information. Like which version of Notepad++ are you using, which version of the plug-in? You can open Notepad++ and go to the menu `? -> Debug info` to copy all relevant info.
