### ISSUE TITLE
Max column length

### ISSUE THREAD

**Issue by pchris7489** [BdR76/CSVLint#97]
Hello,

This is a very good plugin. I came into an issue where CSVLint will stop colorizing or would give me an error when validating the data when my column have to much caracters. I searched in the settings and the documentation but didn't seem to find anything.

I would like to set the maximum column length because depending on the CSV file, I can have a varying column lenght for data validation. This would be good to add this feature in the "detect columns" button because it depends on the CSV I am checking

Thank you for this excellent plugin

**Comment by BdR76** [comment]
Thanks for posting the issue, I suspect this has to do with the column auto-detection somehow detecting the maximum column lengths incorrectly for certain column values.

If this is the case, you can manually edit the meta data. So go to the metadata textbox in the bottom-left of the CSV Lint window, and change for example `Width 200` to `Width 300` for the column in question.

If the auto-detection is indeed detecting the lengths incorrectly, can you post an example csv file with those long column values? If you don't want to post privacy sensitive data then can you privately e-mail me the file? Or else edit the CSV with dummy data but which gives the same issues when validating the column lengths?

**Comment by BdR76** [comment]
I can't look into this issue unless you can provide a reproducable example or csv file, so I'll close this one for now.
